### ISSUE TITLE
运行python main.py时错误

### ISSUE THREAD

**Issue by zeroquadrant** [LibraHp/GetQzonehistory#147]
'gbk' codec can't encode character '\xa0' in position 0: illegal multibyte sequence
Traceback (most recent call last):
  File "E:\QZoneHistory\GetQzonehistory\main.py", line 5, in <module>
    import util.RequestUtil as Request
  File "E:\QZoneHistory\GetQzonehistory\util\RequestUtil.py", line 10, in <module>
    cookies = Login.cookie()
              ^^^^^^^^^^^^^^
  File "E:\QZoneHistory\GetQzonehistory\util\LoginUtil.py", line 85, in cookie
    ptqrtoken = ptqrToken(qrsig)
                ^^^^^^^^^^^^^^^^
  File "E:\QZoneHistory\GetQzonehistory\util\LoginUtil.py", line 40, in ptqrToken
    n, i, e = len(qrsig), 0, 0
              ^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

**Comment by zlaazlaa** [comment]
我这里没有复现你的问题，可能是你的终端不支持utf-8编码。
- 可以尝试使用powershell运行
- 也可以切换到gui分支运行`git checkout gui`

**Comment by zlaazlaa** [comment]
@LibraHp 要不要把gui分支设为默认分支，感觉gui版本的体验更好一点
