### ISSUE TITLE
获取空间消息异常

### ISSUE THREAD

**Issue by 00suren** [LibraHp/GetQzonehistory#153]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/d5b2f599-f66b-4028-9723-0c2795725b95">

**Comment by 00suren** [comment]
环境：macos m2pro芯片
版本：1.0.2

**Comment by zlaazlaa** [comment]
是下载的dmg包吗？这个bug修复过了https://github.com/LibraHp/GetQzonehistory/issues/126 https://github.com/LibraHp/GetQzonehistory/pull/130，作者可能还没来得及重新编译，可以下载最新的代码，切换到gui分支，手动运行一下

**Comment by Y1ANZI** [comment]
> <img alt="image" width="779" src="https://private-user-images.githubusercontent.com/53613551/385646099-d5b2f599-f66b-4028-9723-0c2795725b95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODQ3ODYsIm5iZiI6MTczMTQ4NDQ4NiwicGF0aCI6Ii81MzYxMzU1MS8zODU2NDYwOTktZDViMmY1OTktZjY2Yi00MDI4LTk3MjMtMGMyNzk1NzI1Yjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3NTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYmExMzZiZTM0NzdmZDZiZDcyNzU4ZmY2MjBkZDIyYzBhZjYxZTk0MzUwMTQwMGViODVhMTJhY2Y4NjJlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3NzPdZlEhzORcwCqP3ny-Bjjm15SzIOyPQw46utxzRk">

一样

**Comment by 00suren** [comment]
> 是下载的dmg包吗？这个bug修复过了#126 #130 ，作者可能还没来得及重新编译，可以下载最新的代码，切换到gui分支，手动运行一下

好的，我试一下

**Comment by JY-code** [comment]
> 是下载的dmg包吗？这个bug修复过了#126 #130 ，作者可能还没来得及重新编译，可以下载最新的代码，切换到gui分支，手动运行一下

我是下载的最新的命令行版本也报这个错误

**Comment by zlaazlaa** [comment]
> > 是下载的dmg包吗？这个bug修复过了#126 #130 ，作者可能还没来得及重新编译，可以下载最新的代码，切换到gui分支，手动运行一下
> 
> 我是下载的最新的命令行版本也报这个错误

这个限流措施的我只修复了gui版本的

**Comment by StromTao** [comment]
@zlaazlaa gui版本跳过了限流但是数据少了很多

**Comment by JY-code** [comment]
Traceback (most recent call last):
  File "C:\software\GetQzonehistory\main.py", line 1145, in create_card_list_view
    message_content = get_message(i * 100, 100).content
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\software\GetQzonehistory\main.py", line 1054, in get_message
    if message_content.encoding.lower() == 'utf-8':
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'encoding'   换成gui版本后报了一个这样的错误

**Comment by JY-code** [comment]
> > @zlaazlaagui版本跳过了限流但是数据少了很多
> 
> 按理来说不会的，我这边看一下。 你那有报错信息吗

Traceback (most recent call last):
  File "C:\software\GetQzonehistory\main.py", line 1145, in create_card_list_view
    message_content = get_message(i * 100, 100).content
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\software\GetQzonehistory\main.py", line 1054, in get_message
    if message_content.encoding.lower() == 'utf-8':
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'encoding'换成gui版本后报了一个这样的错误

**Comment by Tonyisshady** [comment]
![image](https://github.com/user-attachments/assets/ee2ec80e-04ea-4bec-8683-9de4e309f3fb) 这是什么报错

**Comment by zlaazlaa** [comment]
> ![image](https://github.com/user-attachments/assets/ee2ec80e-04ea-4bec-8683-9de4e309f3fb) 这是什么报错

lower的修复代码已经合并，自行拉取新代码本地运行，或等待release内二进制更新
