### ISSUE TITLE
拉取了最新的gui分支，重复报如下错误

### ISSUE THREAD

**Issue by GISlxz** [LibraHp/GetQzonehistory#163]
Traceback (most recent call last):
  File "C:\Users\zhizhi\Desktop\qq\GetQzonehistory\main.py", line 1145, in create_card_list_view
    message_content = get_message(i * 100, 100).content
  File "C:\Users\zhizhi\Desktop\qq\GetQzonehistory\main.py", line 1054, in get_message
    if message_content.encoding.lower() == 'utf-8':
AttributeError: 'str' object has no attribute 'encoding'

**Comment by cdogbaigei** [comment]
我也是这样

**Comment by GISlxz** [comment]
主要是我发现我网页端正常访问qq空间都打不开“与我相关”的消息列表

**Comment by zlaazlaa** [comment]
> Traceback (most recent call last): File "C:\Users\zhizhi\Desktop\qq\GetQzonehistory\main.py", line 1145, in create_card_list_view message_content = get_message(i * 100, 100).content File "C:\Users\zhizhi\Desktop\qq\GetQzonehistory\main.py", line 1054, in get_message if message_content.encoding.lower() == 'utf-8': AttributeError: 'str' object has no attribute 'encoding'

帮忙测试一下这个pr，是否还会出现上述问题 https://github.com/LibraHp/GetQzonehistory/pull/165
