### ISSUE TITLE
[Bug]: AttributeError 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by frozenfish0x** [LibraHp/GetQzonehistory#173]
![image](https://github.com/user-attachments/assets/0f9e485a-4178-4ed9-9af5-beb75a51806c)

**Comment by magical1998** [comment]
腾讯修的还是快啊

**Comment by YIYIYI12** [comment]
有没有交流群啊

**Comment by akan1n9** [comment]
同问

**Comment by fusheng216** [comment]
作者大大这个情况什么时候可以解决啊？

**Comment by zlaazlaa** [comment]
修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码

**Comment by YIYIYI12** [comment]
> 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码

跑了新代码，一直在刚开始的加载页面

**Comment by zlaazlaa** [comment]
> > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> 
> 解释器是3.9还是3.10

3.9以上

**Comment by zlaazlaa** [comment]
> > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> 
> 跑了新代码，一直在刚开始的加载页面

有报错吗，截图看看

**Comment by YIYIYI12** [comment]
> > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > 
> > 
> > 跑了新代码，一直在刚开始的加载页面
> 
> 有报错吗，截图看看

![Uploading 屏幕截图 2024-11-13 203654.png…]()

**Comment by YIYIYI12** [comment]
> 有报错吗，截图看看

![Uploading 屏幕截图 2024-11-13 203654.png…]()

**Comment by zlaazlaa** [comment]
> > 有报错吗，截图看看
> 
> ![Uploading 屏幕截图 2024-11-13 203654.png…]()
> 

图片好像没传上来

**Comment by YIYIYI12** [comment]
> 有报错吗，截图看看
![屏幕截图 2024-11-13 203654](https://github.com/user-attachments/assets/1dfc2717-68b5-4c10-9d06-a32971983dad)

**Comment by magical1998** [comment]
![1731501607542](https://github.com/user-attachments/assets/38ea8770-afd1-4878-b210-a03c715bf87b)
貌似是一直在这个载入页面

**Comment by YIYIYI12** [comment]
> > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > 
> > 
> > 跑了新代码，一直在刚开始的加载页面
> 
> 有报错吗，截图看看

不好意思重新传了

**Comment by zlaazlaa** [comment]
> > 有报错吗，截图看看
> ![屏幕截图 2024-11-13 203654](https://github.com/user-attachments/assets/1dfc2717-68b5-4c10-9d06-a32971983dad)
> 

直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了

**Comment by zlaazlaa** [comment]
> > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > 
> > > 
> > > 跑了新代码，一直在刚开始的加载页面
> > 
> > 有报错吗，截图看看
> 
> 不好意思重新传了

直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了

**Comment by magical1998** [comment]
(pytorch) PS J:\cityscapes\GetQzonehistory-gui> flet run              
F:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Traceback (most recent call last):
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1103, in get_message_count
    response = get_message(total, 10)
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1055, in get_message
    mc = get_message_unsafe(start, count)
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1061, in get_message_unsafe
    g_tk = bkn(cookies['p_skey'])
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1139, in create_card_list_view
    page.client_storage.set(f"{now_login_user.uin}_message_count", count)
AttributeError: 'NoneType' object has no attribute 'uin'

Traceback (most recent call last):
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1103, in get_message_count
    response = get_message(total, 10)
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1055, in get_message
    mc = get_message_unsafe(start, count)
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1061, in get_message_unsafe
    g_tk = bkn(cookies['p_skey'])
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1139, in create_card_list_view
    page.client_storage.set(f"{now_login_user.uin}_message_count", count)
AttributeError: 'NoneType' object has no attribute 'uin'
控制端报的是这个错误

**Comment by magical1998** [comment]
> > > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > > 
> > > > 
> > > > 跑了新代码，一直在刚开始的加载页面
> > > 
> > > 
> > > 有报错吗，截图看看
> > 
> > 
> > 不好意思重新传了
> 
> 直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了

与我相关里面就是一直在缓冲

**Comment by zlaazlaa** [comment]
> > > > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > > > 
> > > > > 
> > > > > 跑了新代码，一直在刚开始的加载页面
> > > > 
> > > > 
> > > > 有报错吗，截图看看
> > > 
> > > 
> > > 不好意思重新传了
> > 
> > 直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了
> 
> 与我相关里面就是一直在缓冲

那就是又封了🤡

**Comment by zlaazlaa** [comment]
> (pytorch) PS J:\cityscapes\GetQzonehistory-gui> flet run              
> F:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
>   from pandas.core import (
> Traceback (most recent call last):
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1103, in get_message_count
>     response = get_message(total, 10)
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1055, in get_message
>     mc = get_message_unsafe(start, count)
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1061, in get_message_unsafe
>     g_tk = bkn(cookies['p_skey'])
> TypeError: 'NoneType' object is not subscriptable
> 
> Traceback (most recent call last):
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1139, in create_card_list_view
>     page.client_storage.set(f"{now_login_user.uin}_message_count", count)
> AttributeError: 'NoneType' object has no attribute 'uin'
> 
> Traceback (most recent call last):
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1103, in get_message_count
>     response = get_message(total, 10)
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1055, in get_message
>     mc = get_message_unsafe(start, count)
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1061, in get_message_unsafe
>     g_tk = bkn(cookies['p_skey'])
> TypeError: 'NoneType' object is not subscriptable
> 
> Traceback (most recent call last):
>   File "J:\cityscapes\GetQzonehistory-gui\main.py", line 1139, in create_card_list_view
>     page.client_storage.set(f"{now_login_user.uin}_message_count", count)
> AttributeError: 'NoneType' object has no attribute 'uin'
> 控制端报的是这个错误

你这个也是获取不到了，腾讯接口封了，再等等，等他解吧

**Comment by magical1998** [comment]
这tx手真快啊

**Comment by fusheng216** [comment]
现在可以了好像

**Comment by YIYIYI12** [comment]
> > > > > > > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 跑了新代码，一直在刚开始的加载页面
> > > > > > > 
> > > > > > > 
> > > > > > > 有报错吗，截图看看
> > > > > > 
> > > > > > 
> > > > > > 不好意思重新传了
> > > > > 
> > > > > 
> > > > > 直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了
> > > > 
> > > > 
> > > > 与我相关里面就是一直在缓冲
> > > 
> > > 
> > > 那就是又封了🤡
> > 
> > 
> > 开了
> 
> ok

![问题](https://github.com/user-attachments/assets/1f4aa723-867d-4d22-836f-51a884597e84)
我的好像还是有问题

**Comment by zlaazlaa** [comment]
> > > > > > > > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 跑了新代码，一直在刚开始的加载页面
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 有报错吗，截图看看
> > > > > > > 
> > > > > > > 
> > > > > > > 不好意思重新传了
> > > > > > 
> > > > > > 
> > > > > > 直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了
> > > > > 
> > > > > 
> > > > > 与我相关里面就是一直在缓冲
> > > > 
> > > > 
> > > > 那就是又封了🤡
> > > 
> > > 
> > > 开了
> > 
> > ok
> 
> ![问题](https://github.com/user-attachments/assets/1f4aa723-867d-4d22-836f-51a884597e84)
> 我的好像还是有问题

qq空间网页版，与我相关，有数据吗

**Comment by YIYIYI12** [comment]
> > > > > > > > > > > 修复的PR刚刚被合并了，等待作者编译新二进制，或自行运行新代码
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 跑了新代码，一直在刚开始的加载页面
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 有报错吗，截图看看
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不好意思重新传了
> > > > > > > 
> > > > > > > 
> > > > > > > 直接在电脑浏览器登录qq空间网页版，点击“与我相关”，可以查看吗？腾讯好像又把接口封了
> > > > > > 
> > > > > > 
> > > > > > 与我相关里面就是一直在缓冲
> > > > > 
> > > > > 
> > > > > 那就是又封了🤡
> > > > 
> > > > 
> > > > 开了
> > > 
> > > 
> > > ok
> > 
> > 
> > ![问题](https://private-user-images.githubusercontent.com/118703096/385769661-1f4aa723-867d-4d22-836f-51a884597e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDM5MDEsIm5iZiI6MTczMTUwMzYwMSwicGF0aCI6Ii8xMTg3MDMwOTYvMzg1NzY5NjYxLTFmNGFhNzIzLTg2N2QtNGQyMi04MzZmLTUxYTg4NDU5N2U4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMzEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDg4NTBmOTQwYjJiMDNmNGU5ZWMzNmQ1NDc0NTM5NzYyMTAxNmU3OGNjMTIxOGVlMWM2ZTE3ODcxNWU2YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-nE5Mkd7pEZcJSnwdcu6hDlWtMAR0M9lQ853Lb9rpmA)
> > 我的好像还是有问题
> 
> qq空间网页版，与我相关，有数据吗

无，一直缓存转圈......

**Comment by Y-Bruce-G** [comment]
应该是一个号一天只能一次刚刚小号可以，第二次扫码就不行了

**Comment by wangyunzi** [comment]
我才刚发现这个好东西啊，就出现这个问题了，悲伤
“[2024-11-14 14:26:54]-[ERROR]处理消息时发生错误: 'NoneType' object has no attribute "lower”
