### ISSUE TITLE
('Connection aborted.', PermissionError(13, 'Permission denied'))

### ISSUE THREAD

**Issue by liesauer** [LibraHp/GetQzonehistory#26]
国内宽带访问国内网站，这不能够出现网络错误吧

```
('Connection aborted.', PermissionError(13, 'Permission denied'))
Traceback (most recent call last):
  File "main.py", line 245, in <module>
  File "main.py", line 199, in cookie
  File "main.py", line 148, in ptqrToken
TypeError: object of type 'NoneType' has no len()
[PYI-4708:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Comment by liesauer** [comment]
这要管理员才能打开？刚刚试了管理员就可以了

**Comment by LibraHp** [comment]
一般情况下，如果你链接的是学校的公用WIFI 或者是其他公用场所的网络，都有可能引起请求失败的问题，不需要使用管理员模式也可以正常运行

**Comment by liesauer** [comment]
> 一般情况下，如果你链接的是学校的公用WIFI 或者是其他公用场所的网络，都有可能引起请求失败的问题，不需要使用管理员模式也可以正常运行

感觉并不是这个原因，我公司、家里都试过，也是一直这样，一用管理员模式运行就能打开了，直接双击就不行
